package pl.wendigo.chrome.domain.security

/**
 * Security
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class SecurityDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Enables tracking security state changes.
	 */
	fun enable() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("$domainName.enable", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Disables tracking security state changes.
	 */
	fun disable() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("$domainName.disable", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Displays native dialog with the certificate details.
	 */
	fun showCertificateViewer() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("$domainName.showCertificateViewer", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

  /**
   * The security state of the page changed.
   */
  fun onSecurityStateChanged() : io.reactivex.Flowable<SecurityStateChangedEvent> {
      return connection.captureEvents("$domainName.securityStateChanged", SecurityStateChangedEvent::class.java)
  }

  companion object {
    private const val domainName = "Security"
  }
}

data class SecurityStateChangedEvent (
  /**
   * Security state.
   */
  val securityState : SecurityState,

  /**
   * True if the page was loaded over cryptographic transport such as HTTPS.
   */
  val schemeIsCryptographic : Boolean,

  /**
   * List of explanations for the security state. If the overall security state is `insecure` or `warning`, at least one corresponding explanation should be included.
   */
  val explanations : Array<SecurityStateExplanation>,

  /**
   * Information about insecure content on the page.
   */
  val insecureContentStatus : InsecureContentStatus,

  /**
   * Overrides user-visible description of the state.
   */
  val summary : String? = null

)

