package pl.wendigo.chrome.domain.applicationcache

/**
 * ApplicationCacheDomain represents remote debugger protocol domain.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class ApplicationCacheDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Returns array of frame identifiers with manifest urls for each frame containing a document associated with some application cache.
	 */
	fun getFramesWithManifests() : io.reactivex.Flowable<GetFramesWithManifestsResponse> {
        return connection.runAndCaptureResponse("$domainName.getFramesWithManifests", null, GetFramesWithManifestsResponse::class.java)
	}

	/**
	 * Enables application cache domain notifications.
	 */
	fun enable() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("$domainName.enable", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Returns manifest URL for document in the given frame.
	 */
	fun getManifestForFrame(input : GetManifestForFrameRequest) : io.reactivex.Flowable<GetManifestForFrameResponse> {
        return connection.runAndCaptureResponse("$domainName.getManifestForFrame", input, GetManifestForFrameResponse::class.java)
	}

	/**
	 * Returns relevant application cache data for the document in given frame.
	 */
	fun getApplicationCacheForFrame(input : GetApplicationCacheForFrameRequest) : io.reactivex.Flowable<GetApplicationCacheForFrameResponse> {
        return connection.runAndCaptureResponse("$domainName.getApplicationCacheForFrame", input, GetApplicationCacheForFrameResponse::class.java)
	}

  /**
   *
   */
  fun onApplicationCacheStatusUpdated() : io.reactivex.Flowable<ApplicationCacheStatusUpdatedEvent> {
      return connection.captureEvents("$domainName.applicationCacheStatusUpdated", ApplicationCacheStatusUpdatedEvent::class.java)
  }

  /**
   *
   */
  fun onNetworkStateUpdated() : io.reactivex.Flowable<NetworkStateUpdatedEvent> {
      return connection.captureEvents("$domainName.networkStateUpdated", NetworkStateUpdatedEvent::class.java)
  }

  companion object {
    private const val domainName = "ApplicationCache"
  }
}

data class GetFramesWithManifestsResponse (
  /**
   * Array of frame identifiers with manifest urls for each frame containing a document associated with some application cache.
   */
  val frameIds : Array<FrameWithManifest>

)

data class GetManifestForFrameRequest (
    /**
     * Identifier of the frame containing document whose manifest is retrieved.
     */
    val frameId : pl.wendigo.chrome.domain.page.FrameId

)

data class GetManifestForFrameResponse (
  /**
   * Manifest URL for document in the given frame.
   */
  val manifestURL : String

)

data class GetApplicationCacheForFrameRequest (
    /**
     * Identifier of the frame containing document whose application cache is retrieved.
     */
    val frameId : pl.wendigo.chrome.domain.page.FrameId

)

data class GetApplicationCacheForFrameResponse (
  /**
   * Relevant application cache data for the document in given frame.
   */
  val applicationCache : ApplicationCache

)

data class ApplicationCacheStatusUpdatedEvent (
  /**
   * Identifier of the frame containing document whose application cache updated status.
   */
  val frameId : pl.wendigo.chrome.domain.page.FrameId,

  /**
   * Manifest URL.
   */
  val manifestURL : String,

  /**
   * Updated application cache status.
   */
  val status : Int

)

data class NetworkStateUpdatedEvent (
  /**
   *
   */
  val isNowOnline : Boolean

)

