package pl.wendigo.chrome.domain.domstorage

/**
 * Query and modify DOM storage.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class DOMStorageDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Enables storage tracking, storage events will now be delivered to the client.
	 */
	  fun enable() : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("DOMStorage.enable", null, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * Disables storage tracking, prevents storage events from being sent to the client.
	 */
	  fun disable() : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("DOMStorage.disable", null, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * 
	 */
	  fun getDOMStorageItems(input : GetDOMStorageItemsRequest) : io.reactivex.Flowable<GetDOMStorageItemsResponse> {
        return connection.runAndCaptureResponse("DOMStorage.getDOMStorageItems", input, GetDOMStorageItemsResponse::class.java)
	}

	/**
	 * 
	 */
	  fun setDOMStorageItem(input : SetDOMStorageItemRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("DOMStorage.setDOMStorageItem", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * 
	 */
	  fun removeDOMStorageItem(input : RemoveDOMStorageItemRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("DOMStorage.removeDOMStorageItem", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

  
  /**
   * 
   */
   fun onDomStorageItemsCleared() : io.reactivex.Flowable<DomStorageItemsClearedEvent> {
      return connection.captureEvents(DomStorageItemsClearedEvent::class.java)
   }

  /**
   * 
   */
   fun onDomStorageItemRemoved() : io.reactivex.Flowable<DomStorageItemRemovedEvent> {
      return connection.captureEvents(DomStorageItemRemovedEvent::class.java)
   }

  /**
   * 
   */
   fun onDomStorageItemAdded() : io.reactivex.Flowable<DomStorageItemAddedEvent> {
      return connection.captureEvents(DomStorageItemAddedEvent::class.java)
   }

  /**
   * 
   */
   fun onDomStorageItemUpdated() : io.reactivex.Flowable<DomStorageItemUpdatedEvent> {
      return connection.captureEvents(DomStorageItemUpdatedEvent::class.java)
   }
}





/**
 * Represents requestFrame parameters that can be used with DOMStorage.getDOMStorageItems method call.
 *
 * 
 */
data class GetDOMStorageItemsRequest (
    /**
     * 
     */
    val storageId : StorageId

)

/**
 * Represents responseFrame from DOMStorage. method call.
 *
 * 
 */
data class GetDOMStorageItemsResponse(
  /**
   * 
   */
  val entries : Array<Item>

)

/**
 * Represents requestFrame parameters that can be used with DOMStorage.setDOMStorageItem method call.
 *
 * 
 */
data class SetDOMStorageItemRequest (
    /**
     * 
     */
    val storageId : StorageId,

    /**
     * 
     */
    val key : String,

    /**
     * 
     */
    val value : String

)


/**
 * Represents requestFrame parameters that can be used with DOMStorage.removeDOMStorageItem method call.
 *
 * 
 */
data class RemoveDOMStorageItemRequest (
    /**
     * 
     */
    val storageId : StorageId,

    /**
     * 
     */
    val key : String

)



/**
 * Represents responseFrame from DOMStorage. method call.
 *
 * 
 */
data class DomStorageItemsClearedEvent(
  /**
   * 
   */
  val storageId : StorageId

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "DOMStorage", protocolEventName = "domStorageItemsCleared")

/**
 * Represents responseFrame from DOMStorage. method call.
 *
 * 
 */
data class DomStorageItemRemovedEvent(
  /**
   * 
   */
  val storageId : StorageId,

  /**
   * 
   */
  val key : String

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "DOMStorage", protocolEventName = "domStorageItemRemoved")

/**
 * Represents responseFrame from DOMStorage. method call.
 *
 * 
 */
data class DomStorageItemAddedEvent(
  /**
   * 
   */
  val storageId : StorageId,

  /**
   * 
   */
  val key : String,

  /**
   * 
   */
  val newValue : String

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "DOMStorage", protocolEventName = "domStorageItemAdded")

/**
 * Represents responseFrame from DOMStorage. method call.
 *
 * 
 */
data class DomStorageItemUpdatedEvent(
  /**
   * 
   */
  val storageId : StorageId,

  /**
   * 
   */
  val key : String,

  /**
   * 
   */
  val oldValue : String,

  /**
   * 
   */
  val newValue : String

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "DOMStorage", protocolEventName = "domStorageItemUpdated")

