package pl.wendigo.chrome.domain.rendering

/**
 * This domain allows to control rendering of the page.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class RenderingDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Requests that backend shows paint rectangles
	 */
	  fun setShowPaintRects(input : SetShowPaintRectsRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("Rendering.setShowPaintRects", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * Requests that backend shows debug borders on layers
	 */
	  fun setShowDebugBorders(input : SetShowDebugBordersRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("Rendering.setShowDebugBorders", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * Requests that backend shows the FPS counter
	 */
	  fun setShowFPSCounter(input : SetShowFPSCounterRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("Rendering.setShowFPSCounter", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * Requests that backend shows scroll bottleneck rects
	 */
	  fun setShowScrollBottleneckRects(input : SetShowScrollBottleneckRectsRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("Rendering.setShowScrollBottleneckRects", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

	/**
	 * Paints viewport size upon main frame resize.
	 */
	  fun setShowViewportSizeOnResize(input : SetShowViewportSizeOnResizeRequest) : io.reactivex.Flowable<pl.wendigo.chrome.ResponseFrame> {
        return connection.runAndCaptureResponse("Rendering.setShowViewportSizeOnResize", input, pl.wendigo.chrome.ResponseFrame::class.java)
	}

  }

/**
 * Represents requestFrame parameters that can be used with Rendering.setShowPaintRects method call.
 *
 * Requests that backend shows paint rectangles
 */
data class SetShowPaintRectsRequest (
    /**
     * True for showing paint rectangles
     */
    val result : Boolean

)


/**
 * Represents requestFrame parameters that can be used with Rendering.setShowDebugBorders method call.
 *
 * Requests that backend shows debug borders on layers
 */
data class SetShowDebugBordersRequest (
    /**
     * True for showing debug borders
     */
    val show : Boolean

)


/**
 * Represents requestFrame parameters that can be used with Rendering.setShowFPSCounter method call.
 *
 * Requests that backend shows the FPS counter
 */
data class SetShowFPSCounterRequest (
    /**
     * True for showing the FPS counter
     */
    val show : Boolean

)


/**
 * Represents requestFrame parameters that can be used with Rendering.setShowScrollBottleneckRects method call.
 *
 * Requests that backend shows scroll bottleneck rects
 */
data class SetShowScrollBottleneckRectsRequest (
    /**
     * True for showing scroll bottleneck rects
     */
    val show : Boolean

)


/**
 * Represents requestFrame parameters that can be used with Rendering.setShowViewportSizeOnResize method call.
 *
 * Paints viewport size upon main frame resize.
 */
data class SetShowViewportSizeOnResizeRequest (
    /**
     * Whether to paint size or not.
     */
    val show : Boolean

)



