package pl.wendigo.chrome.domain.rendering

/**
 * This domain allows to control rendering of the page.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class RenderingDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Requests that backend shows paint rectangles
	 */
	fun setShowPaintRects(input : SetShowPaintRectsRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Rendering.setShowPaintRects", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Requests that backend shows debug borders on layers
	 */
	fun setShowDebugBorders(input : SetShowDebugBordersRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Rendering.setShowDebugBorders", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Requests that backend shows the FPS counter
	 */
	fun setShowFPSCounter(input : SetShowFPSCounterRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Rendering.setShowFPSCounter", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Requests that backend shows scroll bottleneck rects
	 */
	fun setShowScrollBottleneckRects(input : SetShowScrollBottleneckRectsRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Rendering.setShowScrollBottleneckRects", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Paints viewport size upon main frame resize.
	 */
	fun setShowViewportSizeOnResize(input : SetShowViewportSizeOnResizeRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Rendering.setShowViewportSizeOnResize", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

  }

data class SetShowPaintRectsRequest (
    /**
     * True for showing paint rectangles
     */
    val result : Boolean

)


data class SetShowDebugBordersRequest (
    /**
     * True for showing debug borders
     */
    val show : Boolean

)


data class SetShowFPSCounterRequest (
    /**
     * True for showing the FPS counter
     */
    val show : Boolean

)


data class SetShowScrollBottleneckRectsRequest (
    /**
     * True for showing scroll bottleneck rects
     */
    val show : Boolean

)


data class SetShowViewportSizeOnResizeRequest (
    /**
     * Whether to paint size or not.
     */
    val show : Boolean

)



