package pl.wendigo.chrome.domain.tethering

/**
 * The Tethering domain defines methods and events for browser port binding.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class TetheringDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Request browser port binding.
	 */
	  fun bind(input : BindRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Tethering.bind", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Request browser port unbinding.
	 */
	  fun unbind(input : UnbindRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Tethering.unbind", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

  
  /**
   * Informs that port was successfully bound and got a specified connection id.
   */
   fun onAccepted() : io.reactivex.Flowable<AcceptedEvent> {
      return connection.captureEvents(AcceptedEvent::class.java)
   }
}

/**
 * Represents request parameters that can be used with Tethering.bind method call.
 *
 * Request browser port binding.
 */
data class BindRequest (
    /**
     * Port number to bind.
     */
    val port : Int

)


/**
 * Represents request parameters that can be used with Tethering.unbind method call.
 *
 * Request browser port unbinding.
 */
data class UnbindRequest (
    /**
     * Port number to unbind.
     */
    val port : Int

)



/**
 * Represents response from Tethering. method call.
 *
 * Informs that port was successfully bound and got a specified connection id.
 */
data class AcceptedEvent(
  /**
   * Port number that was successfully bound.
   */
  val port : Int,

  /**
   * Connection id to be used.
   */
  val connectionId : String

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "Tethering", protocolEventName = "accepted")

