package pl.wendigo.chrome.domain.domdebugger

/**
 * DOM debugging allows setting breakpoints on particular DOM operations and events. JavaScript execution will stop on these operations as if there was a regular breakpoint set.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
class DOMDebuggerDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Sets breakpoint on particular operation with DOM.
	 */
	  fun setDOMBreakpoint(input : SetDOMBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.setDOMBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Removes DOM breakpoint that was set using <code>setDOMBreakpoint</code>.
	 */
	  fun removeDOMBreakpoint(input : RemoveDOMBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.removeDOMBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Sets breakpoint on particular DOM event.
	 */
	  fun setEventListenerBreakpoint(input : SetEventListenerBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.setEventListenerBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Removes breakpoint on particular DOM event.
	 */
	  fun removeEventListenerBreakpoint(input : RemoveEventListenerBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.removeEventListenerBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Sets breakpoint on particular native event.
	 */
	@pl.wendigo.chrome.ProtocolExperimental
    fun setInstrumentationBreakpoint(input : SetInstrumentationBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.setInstrumentationBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Removes breakpoint on particular native event.
	 */
	@pl.wendigo.chrome.ProtocolExperimental
    fun removeInstrumentationBreakpoint(input : RemoveInstrumentationBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.removeInstrumentationBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Sets breakpoint on XMLHttpRequest.
	 */
	  fun setXHRBreakpoint(input : SetXHRBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.setXHRBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Removes breakpoint from XMLHttpRequest.
	 */
	  fun removeXHRBreakpoint(input : RemoveXHRBreakpointRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.removeXHRBreakpoint", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Returns event listeners of the given object.
	 */
	@pl.wendigo.chrome.ProtocolExperimental
    fun getEventListeners(input : GetEventListenersRequest) : io.reactivex.Flowable<GetEventListenersResponse> {
        return connection.runAndCaptureResponse("DOMDebugger.getEventListeners", input, GetEventListenersResponse::class.java)
	}

  }

data class SetDOMBreakpointRequest (
    /**
     * Identifier of the node to set breakpoint on.
     */
    val nodeId : pl.wendigo.chrome.domain.dom.NodeId,

    /**
     * Type of the operation to stop upon.
     */
    val type : DOMBreakpointType

)


data class RemoveDOMBreakpointRequest (
    /**
     * Identifier of the node to remove breakpoint from.
     */
    val nodeId : pl.wendigo.chrome.domain.dom.NodeId,

    /**
     * Type of the breakpoint to remove.
     */
    val type : DOMBreakpointType

)


data class SetEventListenerBreakpointRequest (
    /**
     * DOM Event name to stop on (any DOM event will do).
     */
    val eventName : String,

    /**
     * EventTarget interface name to stop on. If equal to <code>"*"</code> or not provided, will stop on any EventTarget.
     */
    @pl.wendigo.chrome.ProtocolExperimental val targetName : String? = null

)


data class RemoveEventListenerBreakpointRequest (
    /**
     * Event name.
     */
    val eventName : String,

    /**
     * EventTarget interface name.
     */
    @pl.wendigo.chrome.ProtocolExperimental val targetName : String? = null

)


data class SetInstrumentationBreakpointRequest (
    /**
     * Instrumentation name to stop on.
     */
    val eventName : String

)


data class RemoveInstrumentationBreakpointRequest (
    /**
     * Instrumentation name to stop on.
     */
    val eventName : String

)


data class SetXHRBreakpointRequest (
    /**
     * Resource URL substring. All XHRs having this substring in the URL will get stopped upon.
     */
    val url : String

)


data class RemoveXHRBreakpointRequest (
    /**
     * Resource URL substring.
     */
    val url : String

)


data class GetEventListenersRequest (
    /**
     * Identifier of the object to return listeners for.
     */
    val objectId : pl.wendigo.chrome.domain.runtime.RemoteObjectId

)

/**
 * Returns event listeners of the given object.
 */
data class GetEventListenersResponse(
  /**
   * Array of relevant listeners.
   */
  val listeners : Array<EventListener>

)


