package pl.wendigo.chrome.domain.memory

/**
 * MemoryDomain represents remote debugger protocol domain.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class MemoryDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * 
	 */
	  fun getDOMCounters() : io.reactivex.Flowable<GetDOMCountersResponse> {
        return connection.runAndCaptureResponse("Memory.getDOMCounters", null, GetDOMCountersResponse::class.java)
	}

	/**
	 * Enable/disable suppressing memory pressure notifications in all processes.
	 */
	  fun setPressureNotificationsSuppressed(input : SetPressureNotificationsSuppressedRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Memory.setPressureNotificationsSuppressed", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Simulate a memory pressure notification in all processes.
	 */
	  fun simulatePressureNotification(input : SimulatePressureNotificationRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("Memory.simulatePressureNotification", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

  }


/**
 * 
 */
data class GetDOMCountersResponse(
  /**
   * 
   */
  val documents : Int,

  /**
   * 
   */
  val nodes : Int,

  /**
   * 
   */
  val jsEventListeners : Int

)

data class SetPressureNotificationsSuppressedRequest (
    /**
     * If true, memory pressure notifications will be suppressed.
     */
    val suppressed : Boolean

)


data class SimulatePressureNotificationRequest (
    /**
     * Memory pressure level of the notification.
     */
    val level : PressureLevel

)



