package pl.wendigo.chrome.domain.layertree

/**
 * LayerTreeDomain represents remote debugger protocol domain.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
@pl.wendigo.chrome.ProtocolExperimental class LayerTreeDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Enables compositing tree inspection.
	 */
	  fun enable() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("LayerTree.enable", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Disables compositing tree inspection.
	 */
	  fun disable() : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("LayerTree.disable", null, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * Provides the reasons why the given layer was composited.
	 */
	  fun compositingReasons(input : CompositingReasonsRequest) : io.reactivex.Flowable<CompositingReasonsResponse> {
        return connection.runAndCaptureResponse("LayerTree.compositingReasons", input, CompositingReasonsResponse::class.java)
	}

	/**
	 * Returns the layer snapshot identifier.
	 */
	  fun makeSnapshot(input : MakeSnapshotRequest) : io.reactivex.Flowable<MakeSnapshotResponse> {
        return connection.runAndCaptureResponse("LayerTree.makeSnapshot", input, MakeSnapshotResponse::class.java)
	}

	/**
	 * Returns the snapshot identifier.
	 */
	  fun loadSnapshot(input : LoadSnapshotRequest) : io.reactivex.Flowable<LoadSnapshotResponse> {
        return connection.runAndCaptureResponse("LayerTree.loadSnapshot", input, LoadSnapshotResponse::class.java)
	}

	/**
	 * Releases layer snapshot captured by the back-end.
	 */
	  fun releaseSnapshot(input : ReleaseSnapshotRequest) : io.reactivex.Flowable<pl.wendigo.chrome.GenericResponse> {
        return connection.runAndCaptureResponse("LayerTree.releaseSnapshot", input, pl.wendigo.chrome.GenericResponse::class.java)
	}

	/**
	 * 
	 */
	  fun profileSnapshot(input : ProfileSnapshotRequest) : io.reactivex.Flowable<ProfileSnapshotResponse> {
        return connection.runAndCaptureResponse("LayerTree.profileSnapshot", input, ProfileSnapshotResponse::class.java)
	}

	/**
	 * Replays the layer snapshot and returns the resulting bitmap.
	 */
	  fun replaySnapshot(input : ReplaySnapshotRequest) : io.reactivex.Flowable<ReplaySnapshotResponse> {
        return connection.runAndCaptureResponse("LayerTree.replaySnapshot", input, ReplaySnapshotResponse::class.java)
	}

	/**
	 * Replays the layer snapshot and returns canvas log.
	 */
	  fun snapshotCommandLog(input : SnapshotCommandLogRequest) : io.reactivex.Flowable<SnapshotCommandLogResponse> {
        return connection.runAndCaptureResponse("LayerTree.snapshotCommandLog", input, SnapshotCommandLogResponse::class.java)
	}

  
  /**
   * 
   */
   fun onLayerTreeDidChange() : io.reactivex.Flowable<LayerTreeDidChangeEvent> {
      return connection.captureEvents(LayerTreeDidChangeEvent::class.java)
   }

  /**
   * 
   */
   fun onLayerPainted() : io.reactivex.Flowable<LayerPaintedEvent> {
      return connection.captureEvents(LayerPaintedEvent::class.java)
   }
}





data class CompositingReasonsRequest (
    /**
     * The id of the layer for which we want to get the reasons it was composited.
     */
    val layerId : LayerId

)

/**
 * Provides the reasons why the given layer was composited.
 */
data class CompositingReasonsResponse(
  /**
   * A list of strings specifying reasons for the given layer to become composited.
   */
  val compositingReasons : Array<String>

)

data class MakeSnapshotRequest (
    /**
     * The id of the layer.
     */
    val layerId : LayerId

)

/**
 * Returns the layer snapshot identifier.
 */
data class MakeSnapshotResponse(
  /**
   * The id of the layer snapshot.
   */
  val snapshotId : SnapshotId

)

data class LoadSnapshotRequest (
    /**
     * An array of tiles composing the snapshot.
     */
    val tiles : Array<PictureTile>

)

/**
 * Returns the snapshot identifier.
 */
data class LoadSnapshotResponse(
  /**
   * The id of the snapshot.
   */
  val snapshotId : SnapshotId

)

data class ReleaseSnapshotRequest (
    /**
     * The id of the layer snapshot.
     */
    val snapshotId : SnapshotId

)


data class ProfileSnapshotRequest (
    /**
     * The id of the layer snapshot.
     */
    val snapshotId : SnapshotId,

    /**
     * The maximum number of times to replay the snapshot (1, if not specified).
     */
    val minRepeatCount : Int? = null,

    /**
     * The minimum duration (in seconds) to replay the snapshot.
     */
    val minDuration : Double? = null,

    /**
     * The clip rectangle to apply when replaying the snapshot.
     */
    val clipRect : pl.wendigo.chrome.domain.dom.Rect? = null

)

/**
 * 
 */
data class ProfileSnapshotResponse(
  /**
   * The array of paint profiles, one per run.
   */
  val timings : Array<PaintProfile>

)

data class ReplaySnapshotRequest (
    /**
     * The id of the layer snapshot.
     */
    val snapshotId : SnapshotId,

    /**
     * The first step to replay from (replay from the very start if not specified).
     */
    val fromStep : Int? = null,

    /**
     * The last step to replay to (replay till the end if not specified).
     */
    val toStep : Int? = null,

    /**
     * The scale to apply while replaying (defaults to 1).
     */
    val scale : Double? = null

)

/**
 * Replays the layer snapshot and returns the resulting bitmap.
 */
data class ReplaySnapshotResponse(
  /**
   * A data: URL for resulting image.
   */
  val dataURL : String

)

data class SnapshotCommandLogRequest (
    /**
     * The id of the layer snapshot.
     */
    val snapshotId : SnapshotId

)

/**
 * Replays the layer snapshot and returns canvas log.
 */
data class SnapshotCommandLogResponse(
  /**
   * The array of canvas function calls.
   */
  val commandLog : Array<Any>

)


/**
 * 
 */
data class LayerTreeDidChangeEvent(
  /**
   * Layer tree, absent if not in the comspositing mode.
   */
  val layers : Array<Layer>? = null

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "LayerTree", protocolEventName = "layerTreeDidChange")

/**
 * 
 */
data class LayerPaintedEvent(
  /**
   * The id of the painted layer.
   */
  val layerId : LayerId,

  /**
   * Clip rectangle.
   */
  val clip : pl.wendigo.chrome.domain.dom.Rect

) : pl.wendigo.chrome.ChromeProtocolEvent(protocolDomain = "LayerTree", protocolEventName = "layerPainted")

