package pl.wendigo.chrome.domain.schema

/**
 * Provides information about the protocol schema.
 *
 * This class was autogenerated by main.go. Do not edit :)
 */
class SchemaDomain internal constructor(private val connection : pl.wendigo.chrome.RemoteChromeConnection) {

	/**
	 * Returns supported domains.
	 */
	fun getDomains() : io.reactivex.Flowable<GetDomainsResponse> {
        return connection.runAndCaptureResponse("Schema.getDomains", null, GetDomainsResponse::class.java)
	}

  }


/**
 * Returns supported domains.
 */
data class GetDomainsResponse(
  /**
   * List of supported domains.
   */
  val domains : Array<Domain>

)


